# Exercícios Numpy

In [ ]:
#Importe o pacote numpy com o nome np.
import numpy as np

In [ ]:
# Crie o seguinte vetor unidimensional (1D):
vetor = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
print(vetor)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Qual é o comprimento len do vetor?
print(len(vetor))   

10


In [ ]:
#Quantas dimensões ndim o vetor possui?
print(vetor.ndim)

1


In [ ]:
#O que a função shape retorna?
print(vetor.shape)

(10,)


In [ ]:
#Crie a variável pares e extraia todos os números pares do vetor para ela:
pares = []

for par in vetor:
  if par % 2 == 0: pares.append(par)

print(pares)

[0, 2, 4, 6, 8]


In [ ]:
#Substitua todos os elementos ímpares do vetor por -1, em seguida, ordene os resultados:
vetor = np.arange(0, 10) 

for i in vetor:
  if i % 2 != 0: vetor[i] = -1

print(vetor)
vetor.sort()
vetor

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([-1, -1, -1, -1, -1,  0,  2,  4,  6,  8])

In [ ]:
#Converta o vetor unidimensional (1D) abaixo para uma matriz (2D) com 4 linhas. Dica: reshape.

vetor = np.arange(12)
vetor = vetor.reshape(4,3)
print(vetor)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#Obtenha os itens em comum, ou seja, a intersecção dos vetores a e b abaixo:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 4, 6, 8, 10])

res = np.intersect1d(a,b)

print(res)

[2 4 6]


In [ ]:
#Retorne os valores únicos do vetor a que não estão no vetor b (diferença).

a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])

res = np.setdiff1d(a,b)
print(res)              

[1 3]


In [ ]:
#Retorne um vetor com as posições (índices) onde os elementos do vetor a sãos iguais aos elementos do vetor b. Dica: where.

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 4, 3, 4, 10, 6])

print(np.where(a == b))

(array([2, 3, 5]),)


In [ ]:
#Obtenha todos os itens entre 5 e 15 do vetor a = [0, 1, 2, 3, . . ., 20].
a = np.arange(21)
a
print(np.where((a > 5) & (a < 15)))

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14]),)


In [ ]:
#Crie e imprima um vetor com 5 números aleatórios, sem seguida, obtenha os valores máximo e mínimo dele e mostre na tela.
vetor = np.random.randint(100, size=(5))
print(vetor)
print("Máximo:", vetor.max(), "Mínimo:", vetor.min())

[96 16 41 26 87]
Máximo: 96 Mínimo: 16


In [ ]:
#Crie a seguinte matriz:
matriz = np.array([ [7,8,9],[4,5,6],[1,2,3] ])
matriz

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
#Troque de lugar a primeira coluna com a útltima coluna da matriz.
matriz = np.array([ [7,8,9],[4,5,6],[1,2,3] ])
matriz[:, [2, 0]] = matriz[:, [0, 2]] 
print(matriz)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Troque de lugar a primeira linha com a útltima linha da matriz.
matriz = np.array([ [7,8,9],[4,5,6],[1,2,3] ])
matriz[(0,2), :] = matriz[(2,0), :] 
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Crie uma matriz 7 × 5 preenchida com números decimais aleatórios entre 1 e 5.
matriz = np.random.randint(1,6,size=(7,5))
print(matriz)

[[1 3 3 5 2]
 [2 2 3 5 2]
 [5 1 5 4 3]
 [1 1 1 3 1]
 [2 3 2 1 4]
 [2 4 4 2 2]
 [3 5 1 2 5]]


In [ ]:
#Qual é o comprimento len da matriz?
print(len(matriz))

7


In [ ]:
#Quantas dimensões ndim a matriz possui?
print(matriz.ndim)

2


In [ ]:
#O que a função shape retorna?
print(matriz.shape)

(7, 5)


# EXERCÍCIO: Análise de Dados dos Jogadores da FIFA 


In [140]:
#Importe o pacote numpy com o nome np.
import numpy as np

In [141]:
#Carregue o conjunto de dados da Fifa disponível na pasta (data/fifa.csv), ignorando a coluna foto, para uma matriz em uma variavel chamada dados. Dicas:
#Pesquise pela função genfromtxt;
#Não esqueça de especificar a codificação (encoding) como UTF-8;
#Ignore o cabeçalho dos dados usando o parâmetro skip_header=True

dados = np.genfromtxt('fifa.csv', delimiter=',', encoding='utf-8', skip_header=True, dtype=object, usecols=[0,1,2,4,5,6,7,8,9,10,11,12,13])
dados

array([[b'158023', b'L. Messi', b'31', ..., b'72.121', b'RF', b'10'],
       [b'20801', b'Cristiano Ronaldo', b'33', ..., b'83.007', b'ST',
        b'7'],
       [b'190871', b'Neymar Jr', b'26', ..., b'68.039', b'LW', b'10'],
       ...,
       [b'241638', b'B. Worman', b'16', ..., b'67.132', b'ST', b'33'],
       [b'246268', b'D. Walker-Rice', b'17', ..., b'69.853', b'RW',
        b'34'],
       [b'246269', b'G. Nugent', b'16', ..., b'79.832', b'CM', b'33']],
      dtype=object)

In [ ]:
#Quantas linhas foram lidas do arquivo?
print(len(dados))

18207


In [ ]:
#Quantas dimensões sua variável dados possui?
np.ndim(dados)

2

In [ ]:
#O que a função shape retorna?
print(np.shape(dados))

(18207, 13)


In [ ]:
#Mostre o dado que está na 3ª linha da 4ª coluna?
print(dados[2,3])

b'Brasil'


In [ ]:
#Exiba os dados da primeira linha do dataset.
print(dados[:1])

[[b'158023' b'L. Messi' b'31' b'Argentina' b'94' b'94' b'FC Barcelona'
  b'Esquerdo' b'5' b'170' b'72.121' b'RF' b'10']]


In [ ]:
#Mostre as 5 primeiras linhas do conjunto de dados.
print(dados[:5])

[[b'158023' b'L. Messi' b'31' b'Argentina' b'94' b'94' b'FC Barcelona'
  b'Esquerdo' b'5' b'170' b'72.121' b'RF' b'10']
 [b'20801' b'Cristiano Ronaldo' b'33' b'Portugal' b'94' b'94' b'Juventus'
  b'Direito' b'5' b'188' b'83.007' b'ST' b'7']
 [b'190871' b'Neymar Jr' b'26' b'Brasil' b'92' b'93'
  b'Paris Saint-Germain' b'Direito' b'5' b'175' b'68.039' b'LW' b'10']
 [b'193080' b'De Gea' b'27' b'Espanha' b'91' b'93' b'Manchester United'
  b'Direito' b'4' b'193' b'76.204' b'GK' b'1']
 [b'192985' b'K. De Bruyne' b'27' b'B\xe9lgica' b'91' b'92'
  b'Manchester City' b'Direito' b'4' b'155' b'69.853' b'RCM' b'7']]


In [ ]:
#Selecione todas as linhas da coluna nome (segunda coluna). Dica: use o operador :
print(dados[:, 1])

[b'L. Messi' b'Cristiano Ronaldo' b'Neymar Jr' ... b'B. Worman'
 b'D. Walker-Rice' b'G. Nugent']


In [143]:
#Inicialize um vetor de inteiros NumPy chamado: idades; com todas as linhas da coluna idade (3ª coluna).

idades = dados[:, 2].astype('int')
idades

array([31, 33, 26, ..., 16, 17, 16])

In [144]:
#Qual é a média de idades dos jogadores?
print(idades.mean())

25.122205745043114


In [145]:
#Qual é a maior idade do conjunto de dados?

print(idades.max())

45


In [100]:
#Qual é a menor idade do conjunto de dados?

print(idades.min())

16


In [150]:
#Selecione todos os jogadores que possuem a maior idade deste conjunto de dados. Quantas linhas retornaram?
maior_idade = np.where(idades == 45)
mais_velhos = dados[maior_idade]
print(len(mais_velhos))

1


In [149]:
#Selecione todos os jogadores que possuem a menor idade deste conjunto de dados. Quantas linhas retornaram?
menor_idade = np.where(idades == 16)
mais_novos = dados[menor_idade]
print(len(mais_novos))

42


In [154]:
#Selecione todos os jogadores brasileiros para uma variável chamada dados_brasil. Use b'Brasil' para fazer a comparação.
condicao = np.where(dados[:, 3] == b'Brasil')
dados_brasil = dados[condicao]

In [156]:
#Quantos são os jogadores brasileiros?
print(len(dados_brasil), "Jogadores")

69 Jogadores


In [165]:
#Para as colunas idade, altura e peso, calcule: Média, Mediana, Máximo e Mínimo
idades_brasileiros = dados_brasil[:, 2].astype('float')
alturas_brasileiros = dados_brasil[:, 9].astype('float')
pesos_brasileiros = dados_brasil[:, 10].astype('float')

idade_media = round(idades_brasileiros.mean(), 2)
idade_mediana = np.median(idades_brasileiros) 
idade_maxima = idades_brasileiros.max()
idade_minima = idades_brasileiros.min()

altura_media = round(alturas_brasileiros.mean())
altura_mediana = np.median(alturas_brasileiros) 
altura_maxima = alturas_brasileiros.max()
altura_minima = alturas_brasileiros.min()

peso_medio = round(pesos_brasileiros.mean())
peso_mediano = np.median(pesos_brasileiros) 
peso_maximo = pesos_brasileiros.max()
peso_minimo = pesos_brasileiros.min()

print(f"Idades: Média - {idade_media} Mediana: {idade_mediana} Máxima: {idade_maxima} Mínima: {idade_minima}")
print(f"Alturas: Média - {altura_media} Mediana: {altura_mediana} Máxima: {altura_maxima} Mínima: {altura_minima}")
print(f"Pesos: Média - {peso_medio} Mediana: {peso_mediano} Máxima: {peso_maximo} Mínima: {peso_minimo}")

Idades: Média - 28.03 Mediana: 28.0 Máxima: 35.0 Mínima: 21.0
Alturas: Média - 175 Mediana: 175.0 Máxima: 198.0 Mínima: 152.0
Pesos: Média - 77 Mediana: 76.204 Máxima: 92.986 Mínima: 59.874


In [171]:
#Calcule o desvio padrão da reputação dos jogadores brasileiros
reputacao_brasileiros = dados_brasil[:, 8].astype('float')

desvio = round(np.std(reputacao_brasileiros), 2)
print(f"Desvio padrão: {desvio}")

Desvio padrão: 1.01


In [175]:
#Qual jogador brasileiro tem menor pontencial?
potencial_brasileiros = dados_brasil[:, 5].astype('float').min()

print(f"Menor potencial: {potencial_brasileiros}")

Menor potencial: 79.0
